Space_Socials/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('test/',views.TestView.as_view(),name='test'),
    path('thanks/',views.ThanksView.as_view(),name='thanks'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts'))
]

groups/urls.py
from django.urls import path
from . import views
app_name = 'groups'
urlpatterns = [
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug>/',views.SingleGroup.as_view(),name='single'),
    path('join/<slug>/',views.JoinGroup.as_view(),name='join'),
    path('leave/<slug>/',views.LeaveGroup.as_view(),name='leave'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<pk>/',views.DeletePost.as_view(),name='delete'),
]

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.

import misaka

from django.contrib.auth import get_user_model
from django import template
register = template.Library()
User = get_user_model()


class Group(models.Model):
    name = models.CharField(max_length=30,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True,default='')         #url generated out of group name
    description = models.CharField(max_length=264,blank=True,default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through='GroupMember')


    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html  = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    def Meta(self):
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)

    def __str__(self):
        self.user.username

    class Meta:
        unique_together = ['group','user']

groups/forms.py
# from django import forms
# from accounts.models import Group
#
#
# class GroupForm(forms.ModelForm):
#     class Meta:
#         model = Group
#         fields ('name','description','admin')

groups/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.views.generic import CreateView,UpdateView,DetailView,ListView,DeleteView,RedirectView
from django.urls import reverse
from django.contrib import messages

from groups.models import Group,GroupMember
# Create your views here.

class CreateGroup(LoginRequiredMixin,CreateView):
    fields = ('name','description')
    model = Group

class SingleGroup(DetailView):
    model = Group

class ListGroups(ListView):
    model = Group

class JoinGroup(LoginRequiredMixin,RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        group =get_object_or_404(Group,slug=self.kwargs.get('slug'))
        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except:
            messages.warning(self.request,'Warning already a member')
        else:
            messages.success(self.request,'You are now a member')
        return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        try:
            membership = GroupMember.objects.filter(user=self.request.user,group__slug=self.kwargs.get('slug')).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are not in this group')
        else:
            membership.delete()
            messages.success(self.request,'You have left the group')
        return super().get(request,*args,**kwargs)



groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        {% block pre_group %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block post_group %}{% endblock %}
    </div>
</div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}


{% block pre_group %}
<h1>{{group.name}}</h1>
<h2>Member count: {{group.members.count}}</h2>
<div class="content">
    {% if user in group.members.all %}
    <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-warning btn-pill">Leave</a>
    {% else %}
    <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-warning btn-pill">Join</a>
    {% endif %}
</div>
{% endblock %}


{% block group_content %}

<div class="col-md-8">
    {% if group.posts.count == 0 %}
    <h2>No posts in this group yet!</h2>
    {% else %}
        {% for post in  group.posts.all %}
        {% include 'posts/_post.html' %}
        {% endfor %}
    {% endif %}
</div>
{% endblock %}


groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap5 %}
{% block group_content %}
<h2>Create a new group!</h2>
<form method="post" id="groupForm" action="{% url 'groups:create' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Create" class="btn btn-primary btn-large">
</form>
{% endblock %}

groups/templates/groups/group_list.html
{%  extends 'groups/group_base.html' %}
{% block pre_group %}
<div class="col-md-8">
    <div class="content">
        {% if user.is_authenticated %}
        <h2>Welcome Back!<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a></h2>
        {% endif %}
        <h2>Groups</h2>
        <p>Welcome to groups page!</p>
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class="btn btn-pill btn-primary">Create New Group!</a>
    <a href="{% url 'posts:create' %}" class="btn btn-primary btn-pill">Create Post!</a>
    {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
    <div class="list-group">
        {% for group in group_list %}

        <a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item">
            <h3 class="title list-group-item-heading">{{group.name}}</h3>
            <div class="container-fluid list-group-item-text ">{{group.description_html|safe}}
            <div class="row">
                <div class="col-md-4">
                    members {{group.members.count}}
                </div>
                <div class="col-md-4">
                    posts {{group.posts.count}}
                </div>
            </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}