Space_Socials/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('test/',views.TestView.as_view(),name='test'),
    path('thanks/',views.ThanksView.as_view(),name='thanks'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts'))
]

accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<pk>/',views.DeletePost.as_view(),name='delete'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/self.css' %}" />

    <title>Space Socials</title>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Space Socials</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:create' %}">Post</a>
          </li>
          {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
        </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'groups:create' %}">Create Group</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
          </li>
          {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">Sign up</a>
        </li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>
<canvas id="stars"></canvas>

<div class="slider">
  
    <input type="range" min="0.5" max="15" value="2" step="0.5">

{% block content %}
{% endblock %}

  </div>


</body>

   <script type="text/javascript" src="{% static 'js/self.js' %}"></script>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-3">
    <h1 class="selfone">Welcome to Space Socials!</h1>
</div>
{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-3">
    <h1>You are now Logged In!</h1>
</div>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-3">
    <h1>Thanks for using Space Socials!</h1>
</div>
{% endblock %}