Space_Socials/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('test/',views.TestView.as_view(),name='test'),
    path('thanks/',views.ThanksView.as_view(),name='thanks'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts'))
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<pk>/',views.DeletePost.as_view(),name='delete'),
]

posts/models.py
from django.db import models
from django.urls import reverse
from groups.models import Group
from django.conf import settings
from django.utils.timezone import now
# Create your models here.

import misaka

from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    message = models.TextField(max_length=200)
    message_html = models.TextField(editable=False,default='')
    group = models.ForeignKey(Group,on_delete=models.CASCADE,related_name='posts',null=True,blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='posts')
    create_date = models.DateTimeField(default=now)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})

    class Meta:
        ordering = ['-create_date']
        unique_together = ['user','message']

posts/forms.py
# from django import forms
# from accounts.models import Post
#
#
# class PostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = ('message','group')

posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView,DetailView,DeleteView,ListView
from django.http import Http404
from braces.views import SelectRelatedMixin
from django.contrib import messages
# Create your views here.

from . import models
from . import forms
from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

class PostList(SelectRelatedMixin,ListView):
    model = models.Post
    select_related = ('user','group')

class UserPosts(ListView):
    model = models.Post
    template_name = 'post/user_post.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin,DetailView):
    model = models.Post
    select_related = ('user','group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact = self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,CreateView):
    model = models.Post
    fields = ('message','group')

    def form_valid(self, form ):
        query_se = list(Group.objects.filter(members=self.request.user).values_list('name',flat=True))
        current = form.cleaned_data['group']        #get value from form field
        if str(current) in query_se:
            self.object  = form.save(commit = False)
            self.object.user = self.request.user
            self.object.save()
            return super().form_valid(form)
        else:
            messages.error(self.request, "You are not member of this group.")
            return super().get(request=form)




class DeletePost(DeleteView,SelectRelatedMixin,LoginRequiredMixin):
    model = models.Post
    select_related = ('user','group')
    success_url = reverse_lazy('posts:all')
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        message.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)


posts/templates/posts/_post.html
<div class="post media">
    <h3>{{post.message_html|safe}}</h3>
    <div class="media-body">
        <strong>{{post.user.username}}</strong>
        <h5 class="media-heading">
            <span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{post.user.username}}</a></span>
            <time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{post.create_date}}</a></time>
        </h5>
        <div class="media-footer">
            {% if user.is_authenticated and post.user == user %}
            <a href="{% url 'posts:delete' pk=post.pk %}" title="Delete" class="btn btn-danger" aria-hidden="true">Delete</a>
            {% endif %}
        </div>
    </div>
</div>

posts/templates/posts/post_base.html
{% extends 'base.html' %}
{% block content %}
<div class="posts-page">
    <div class="container">
        <div class="row">
            {% block pre_post %}
            {% endblock %}
            {% block post_content %}
            {% endblock %}
            {% block post_post %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
<h3>Are you sure you want to delete this Post?</h3>
<div class="posts">
    <div class="post media">
    <h3>{{post.message_html|safe}}</h3>
    <div class="media-body">
        <strong>{{post.user.username}}</strong>
        <h5 class="media-heading">
            <span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}"></a></span>
            <time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}"></a></time>
        </h5>
    </div>
</div>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-danger btn-large">
        <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-success tb-large">Cancel</a>
    </form>
</div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
<div class="col-md-8">
    {% include 'posts/_post.html' %}
</div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap5 %}
{% block post_content %}
<h3>Create new Post</h3>
<form action="{% url 'posts:create' %}" method="post"  id="postForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Post" class="btn btn-primary btn-large">
    {% if messages %}
<ul class="messages">
    {% for message in messages %}

        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <li>
        Important:
        {{ message }}
        </li>
         {% endif %}

    {% endfor %}
</ul>
{% endif %}
</form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}
{% block pre_post %}
{% if request.user.is_authenticated %}           <!--   #add request. before user if it give error-->
<div class="card card-with-shadow">
    <div class="content">
        <h5 class="title opposite">Yours Groups</h5>
        <ul class="list-unstlyed">
            {% for member_group in user.user_groups.all %}      <!--      #get_user_groups is made from related name through template register-->
            <li class="group li-with-bullet"><a href="{% url 'groups:single' slug=member_group.group.slug %}">{{member_group.group.name}}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endif %}

{% endblock %}

{% block post_content %}
<div class="col-md-8">
    {% for post in post_list %}
        {% include 'posts/_post.html' %}
    {% endfor %}
</div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}
{% block pre_block %}
<div class="col-md-4">
    <h1>@{{post_user.username}}</h1>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
    {% for post in post_user %}                 #changing from example
    {% include 'posts/_post.html' %}
    {% endfor %}
</div>
{% endblock %}